name: AI Blogger Automation

on:
  schedule:
    - cron: '0 0,13 * * *' # Runs daily at 0:00AM and 13:00 PM UTC
  workflow_dispatch: # Allows manual trigger from GitHub UI

jobs:
  run-blog-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Blog Bot Script
        env:
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          UNSPLASH_CLIENT_ID: ${{ secrets.UNSPLASH_CLIENT_ID }}
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
          BLOGGER_EMAIL: ${{ secrets.BLOGGER_EMAIL }}
        run: python main.py
